---
global:
  storageClass: 1
group: users
customTLS:
  enabled: true
ltb-passwd:
  enabled: false
persistence:
  enabled: true
phpldapadmin:
  enabled: true
  ingress:
    enabled: true
    annotations: {}
    path: /
    hosts:
      - phpldapadmin.gitops.local
  env:
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
replicaCount: 1
