---
  - name: Add Hashicorp DNF Repository
    become: true
    ansible.builtin.template:
      src: templates/hashicorp.repo.j2
      dest: /etc/yum.repos.d/hashicorp.repo
      mode: '0644'
  - name: Create Kubernetes YUM Repository
    become: true
    ansible.builtin.copy:
      src: files/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo
      mode: '0644'
